# <span style="color:blue">0. Importing PyTorch Libraries</span>

In [4]:
# Defining the libraries

import torch
import numpy as np
import pandas as pd

To create a tensor from a Python list, we simply use 'torch.tensor' method on the defined list.

# <span style="color:blue">1. Creating a Tensor from Python list</span>

In [5]:
# Creating tensor from python list

python_list = [[1,2,3]]
x = torch.tensor(python_list)

print(f"Tensored Python List:{x}")
print(f"\nTensor list datatype:{x.dtype}")

Tensored Python List:tensor([[1, 2, 3]])

Tensor list datatype:torch.int64


# <span style="color:blue">2. Creating a Tensor from numpy array</span>

To create a Tensor from a numpy array we use 'from_numpy' method from torch

In [6]:
# Creating tensor from a numpy array

numpy_array = np.array([[1,2,3], [4,5,6]])
y = torch.from_numpy(numpy_array)

print(f"Tensored Numpy array:{y}")
print(f"\nTensor numpy datatype:{y.dtype}")

Tensored Numpy array:tensor([[1, 2, 3],
        [4, 5, 6]])

Tensor numpy datatype:torch.int64


# <span style="color:blue">3. Creating a Tensor from Pandas dataframe</span>

To create a Tensor from Pandas dataframe, the very first thing you need to do is to read the Dataframe as usual
using pandas, followed by extracting the values and then apply the tensor directly on the values

In [7]:
# Creating tensors from a pandas dataframe

df = pd.read_csv('./data.csv')

values = df.values

z = torch.tensor(values)

print(f"Input Dataframe:{df}")
print(f"\nInput values:{values}")
print(f"\nTensor daraframe:{z}")
print(f"\nTensor df datatype:{z.dtype}")


Input Dataframe:   distance_miles  delivery_time_minutes
0            1.60                   7.22
1           13.09                  32.41
2            6.97                  17.47

Input values:[[ 1.6   7.22]
 [13.09 32.41]
 [ 6.97 17.47]]

Tensor daraframe:tensor([[ 1.6000,  7.2200],
        [13.0900, 32.4100],
        [ 6.9700, 17.4700]], dtype=torch.float64)

Tensor df datatype:torch.float64


# <span style="color:blue">4. Creating a Tensor with Predefined values (e.g. zeros, ones, rand)</span>

Sometimes you need to create tensors for specific purposes, like initializing a model's weights and biases before training begins. 
PyTorch allows you to quickly generate tensors filled with placeholder values like **zeros, ones, or random numbers**, which is useful for testing and setup.

To create a zero tensor use 'torch.zeros' method and simply specify the dimensions in the argument

In [8]:
#  Creating tensors with predefined values (zeros, ones, rand)
# Creating tensor with zeros

zeros = torch.zeros(2,3)
print(f"Tensor with zeros:{zeros}")

Tensor with zeros:tensor([[0., 0., 0.],
        [0., 0., 0.]])


To create a tensor with values as 1 use 'torch.ones' method and simply specify the dimensions in the argument

In [9]:
# Creating tensors with ones

ones = torch.ones(2,3)
print(f"Tensor with ones:{ones}")

Tensor with ones:tensor([[1., 1., 1.],
        [1., 1., 1.]])


To create a tensor with random values user 'torch.rand' method followed by specifying the dimensions in the argument.

In [10]:
# Creating tensors with random values

rand = torch.rand(2,3)
print(f"Tensor with random values:{rand}")

Tensor with random values:tensor([[0.4743, 0.0251, 0.0341],
        [0.7703, 0.9008, 0.2010]])


# <span style="color:blue">5. Creating a Sequence Tensor</span>

For situations where you need to generate a sequence of data points, such as a range of values for testing a model's 
predictions, you can create a tensor directly from that sequence.

'torch.arrange' is used to create such sequence.
In the argument, one has to define the initial value (in the following case '0'), the final value (in the following case '1')
followed by the step in which the increment is done.

To put it briefly,
0 ---> 0+ 1 = 1 ----> 1+ 1= 2 ----->......10

In [11]:
# Creating a Sequence tensor

sequence = torch.arange(0, 10, step = 1)
print(f"Sequence Tensor:{sequence}")

Sequence Tensor:tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


# <span style="color:blue">6. Checking Tensor dimensions</span>

To check the dimension (shape) of a tensor we use '.shape' method on the tensor. The o/p will show the corresponding size
of a tensor.

In [13]:
# Checking Tensor dimensions

x= torch.tensor([[1,2,3], [4,5,6]])
print(f"Tensor size:{x.shape}")

Tensor size:torch.Size([2, 3])


# <span style="color:blue">7. Squeeze & Unsqueeze a Tensor</span>

It is necessary to eliminate issue pertaining to tenor shape incompatibility while model training.
This is done by concepts like "Squeeze" & "Unsqueeze".

Unsqueeze does the job of expanding Tensor dimensions by adding a dimension in the Tensor.
The method used is 'unsqueeze()' followed by the dimension to be unsqueezed in the argument.

2D example
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
a.shape
#### (2, 3)


a.unsqueeze(0).shape:
#### (1, 2, 3)



a.unsqueeze(1).shape:
#### (2, 1, 3)


a.unsqueeze(2).shape:
#### (2, 3, 1)

In [15]:
# Expanded Tensor (unsqueeze)

x= torch.tensor([[1,2,3], [4,5,6]])
expanded = x.unsqueeze(0)
print(f"Original tensor:\n{x}")
print(f"\nOriginal tensor size :{x.shape}")
print("_"*45)
print(f"\n\nExpanded tensor:\n{expanded}")
print(f"\nExpanded tensor size:{expanded.shape}")

Original tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])

Original tensor size :torch.Size([2, 3])
_____________________________________________


Expanded tensor:
tensor([[[1, 2, 3],
         [4, 5, 6]]])

Expanded tensor size:torch.Size([1, 2, 3])


Squeeze method -----> 
"Squeeze" on the other hand shrinks a dimension of the tensor. 
The dimension is the one specified in the argument. 
The method used is '.squeeze()'.

2D → 1D example
a = torch.tensor([[1],
                  [2],
                  [3]])
a.shape
#### (3, 1)

squeeze(1)
b = a.squeeze(1)
b.shape
#### (3,)

In [17]:
# Shrunk Tensor (squeeze)

shrunk = expanded.squeeze(0)
print(f"Original tensor:\n{x}")
print(f"\nOriginal tensor size :{expanded.shape}")
print("_"*45)
print(f"\n\nShrunk tensor:\n{shrunk}")
print(f"\nShrunk tensor size:{shrunk.shape}")

Original tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])

Original tensor size :torch.Size([1, 2, 3])
_____________________________________________


Shrunk tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])

Shrunk tensor size:torch.Size([2, 3])


# <span style="color:blue">8. Reshaping a Tensor</span>

Reshaping a Tensor is more or less like restructuring a tensor in the way desired by user. 
We do it by ".reshape" method followed by specifying the dimensions to which we want the Tensor to be reshaped.

In [24]:
# Reshaping a Tensor

print(f"Original Tensor:\n{x}")
print(f"Original Tensor shape\n:{x.shape}")
print("_"*45)

reshaped = x.reshape(3,2)

print(f"Reshaped Tensor:\n{reshaped}")
print(f"Reshaped Tensor shape\n:{reshaped.shape}")

Original Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])
Original Tensor shape
:torch.Size([2, 3])
_____________________________________________
Reshaped Tensor:
tensor([[1, 2],
        [3, 4],
        [5, 6]])
Reshaped Tensor shape
:torch.Size([3, 2])


# <span style="color:blue">9. Transposing a Tensor</span>

Transposing is basically the activity where we swap rows to columns for a defined matrix.
Similarly for Tensors, we use '.transpose(0,1)' method where it tells one to transpose 0 (rows) to 1 (columns).

In [26]:
# Transposing a Tensor

"""Swaps the dimensions of a tensor"""

print(f"Original Tensor:\n{x}")
print(f"Original Tensor shape\n:{x.shape}")
print("_"*45)

transposed = x.transpose(0,1)

print(f"Transposed Tensor:\n{transposed}")
print(f"Transposed Tensor shape\n:{transposed.shape}")

Original Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])
Original Tensor shape
:torch.Size([2, 3])
_____________________________________________
Reshaped Tensor:
tensor([[1, 4],
        [2, 5],
        [3, 6]])
Reshaped Tensor shape
:torch.Size([3, 2])


# <span style="color:blue">10. Concatenating a Tensor</span>

Concatenating is the act of merging multiple tensors to form one unified tensor.

This we do by using 'torch.cat()' method.

The 1st argument will have all the tensors to be merged enclosed in a parantheses.

The 2nd argument will have dim = 0 or 1,

0 - > concatenating on rows
1 - > concatenating on columns.

In [18]:
#Concatenating two tensors

tensor_a = torch.tensor([[1, 2],
                         [3, 4]])
tensor_b = torch.tensor([[5, 6],
                         [7, 8]])

cat_tensor = torch.cat((tensor_a, tensor_b), dim= 1 )

print("TENSOR A:\n\n", tensor_a)
print("\nTENSOR B:\n\n", tensor_b)
print("-"*45)
print("\nCONCATENATED TENSOR (dim=1):\n\n", cat_tensor)

TENSOR A:

 tensor([[1, 2],
        [3, 4]])

TENSOR B:

 tensor([[5, 6],
        [7, 8]])
---------------------------------------------

CONCATENATED TENSOR (dim=1):

 tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


# <span style="color:blue">11. Indexing a Tensor</span>

By far one of the most important applications in Python in general is "Indexing."

Indexing is a concept of accessing element of a array/list/tensor.



____________________________________________________


Always remember, be it rows or columns, positive Indexing starts with 0.

0 - 1st row, 1st column.

& Negative Indexing starts with -1

-1 - Last row.


____________________________________________________


To give an example let us consider 



x = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])



here we can write positive indexing as:
    
x[0] --> [1, 2, 3, 4]
x[1] --> [5, 6, 7, 8]
x[2] --> [9, 10, 11, 12]



_____________________________________________________


which using negative indexing can written as :

x[-3] --> [1, 2, 3, 4]
x[-2] --> [5, 6, 7, 8]
x[-1] --> [9, 10, 11, 12]


______________________________________________________




If I want say, 3rd element of 1st row I have to write:
    
x[0,2]  (Understand, here the 3rd element will be in 2nd index of the column)


In [20]:
x = torch.tensor([
    [1, 2, 3, 4],      #Row0
    [5, 6, 7, 8],      #Row1
    [9, 10, 11, 12]    #Row2
])
print("ORIGINAL TENSOR:\n\n", x)
print("-" * 55)

# Get me 2nd element from Row 1 
single_element_r1C1 = x[0,1]

print("\nINDEXING 2nd element, row 1:", single_element_r1C1)
print("-" * 55)

# Get me 3rd element from Row 1 
single_element_r1C2 = x[0,2]

print("\nINDEXING thir element, row 1:", single_element_r1C2)
print("-" * 55)


# Row 2
second_row = x[1]
print("\nINDEXING Second row:", second_row)
print("-" * 55)


# Row 3
third_row = x[2]
print("\nINDEXING Third row:", third_row)
print("-" * 55)


# Row 3 using negative indexing
third_row_neg = x[-1]
print("\nINDEXING Third row using Negative index:", third_row_neg)
print("-" * 55)


ORIGINAL TENSOR:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
-------------------------------------------------------

INDEXING SINGLE ELEMENT AT [1, 1]: tensor(2)
-------------------------------------------------------

INDEXING SINGLE ELEMENT AT [1, 2]: tensor(3)
-------------------------------------------------------

INDEXING Second row: tensor([5, 6, 7, 8])
-------------------------------------------------------

INDEXING Third row: tensor([ 9, 10, 11, 12])
-------------------------------------------------------

INDEXING Third row using Negative index: tensor([ 9, 10, 11, 12])
-------------------------------------------------------


# <span style="color:blue">12. Slicing a Tensor</span>

Slicing is basically specifying a range of elements to access in an array/lists/tensors.

This is done either by specifying a range in the argument or by specifying just an index.

Here ':' means all

To put it briefly, 

[:,2] will indicate all rows for the third column

Here 1st argument is the row and second is column when we specify ":" at row it means all rows , when at columns it means
all columns


[2,:] indicates all columns for the second row.



When I say [0:2] it indicates elements 0,1

When I say [0:3] it indicates elements 0,1,2.

**The elements in a range [0:n] is always from 0 to n-1**

In [22]:
x = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("ORIGINAL TENSOR:\n\n", x)

ORIGINAL TENSOR:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [38]:
# Getting 1st two rows
# 0:2 sepecifies a range from Row Index 0 to Row Index 2

first_2_rows = x[0:2]
print("First 2 Rows:\n\n", first_2_rows)

First 2 Rows:

 tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [42]:
# Getting 1st row

first_1_row = x[0:1]
print("First 1 Row:\n\n", first_1_row)
print("-" * 100)

First 1 Row:

 tensor([[1, 2, 3, 4]])
----------------------------------------------------------------------------------------------------


Second argument, as discussed above is used for selective extraction of 'columns'. So here we want all rows(:)
fro column 3

In [28]:
# Getting 3rd column

third_col = x[:,2]
print("3rd Column:\n\n", third_col)

3rd Column:

 tensor([ 3,  7, 11])


In [29]:
# Getting 1st column

first_col = x[:,0]
print("1st Column:\n\n", first_col)

1st Column:

 tensor([1, 5, 9])


In [43]:
# Getting every 2nd column from beginning

every_second_col = x[:,::2]
print("Every second column:\n\n", every_second_col)
print("-" * 100)

Every second column:

 tensor([[ 1,  3],
        [ 5,  7],
        [ 9, 11]])
----------------------------------------------------------------------------------------------------


Breakdown of x[:, ::2]

General slicing format:

x[rows, columns]

: (rows)

Means take all rows

::2 (columns)

This is start : stop : step

start → omitted → start at index 0

stop → omitted → go till the end

step = 2 → take every 2nd column

In [44]:
# Getting every 3rd column from beginning

print("-" * 100)
every_third_col = x[:,::3]
print("Every second column:\n\n", every_third_col)

----------------------------------------------------------------------------------------------------
Every second column:

 tensor([[ 1,  4],
        [ 5,  8],
        [ 9, 12]])


In [45]:
# Last column (Again index -1 indicates last and second argument specifies column)
last_col = x[:, -1]

print("\nLAST COLUMN ([:, -1]):", last_col, "\n")


LAST COLUMN ([:, -1]): tensor([ 4,  8, 12]) 



# <span style="color:blue">13. Combining Indexing & Slicing in a Tensor</span>

One can also combine indexing & slicing to pick specif range of data.

In [46]:
x = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("ORIGINAL TENSOR:\n\n", x)

ORIGINAL TENSOR:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [47]:
# Say if I want [3,4], [7,8]

combined = x[0:2, 2:]
print("COMBINED TENSOR:\n\n", combined)

COMBINED TENSOR:

 tensor([[3, 4],
        [7, 8]])


In [53]:
# Say if I want [6,7] [10,11]

combined_2 = x[1:, 1:3]
print("COMBINED TENSOR:\n\n", combined_2)

COMBINED TENSOR:

 tensor([[ 6,  7],
        [10, 11]])


# <span style="color:blue">14. Advanced Indexing in a Tensor (Boolean Masking)</span>

The concept of Boolean Masking is to apply Boolean logic to an existing Tensor

In [54]:
x = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("ORIGINAL TENSOR:\n\n", x)

ORIGINAL TENSOR:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [56]:
# Say if i want values greater than 5

mask = x > 5

value_greater_than_five = x[mask]


print("Value greater than 5 tensor:\n\n", value_greater_than_five)

Value greater than 5 tensor:

 tensor([ 6,  7,  8,  9, 10, 11, 12])


In [59]:
# Alternatively you can also write

value_greater_than_five = x[x > 5]
print("Value greater than 5 tensor:\n\n", value_greater_than_five)

Value greater than 5 tensor:

 tensor([ 6,  7,  8,  9, 10, 11, 12])
